export type RootStackParamList = {
  Home: undefined;
  Profile: undefined;
  Mypage: undefined;
  MyBuyTime: undefined;
  Notify: undefined;
  MySellTime: undefined;
  Pay: undefined;
  Appeal: undefined;
  AppealWrite: undefined;
  StackNavigator: undefined;
  SignUp: undefined;
  ChatScreen: {roomId: number};
  Chatting: undefined;
  SignIn: undefined;
  BottomTabNavigation: undefined;
  Setting: undefined;
  Logout: undefined;
  DeleteMem: undefined;
  NameChange: undefined;
  StackNavigators: undefined;
  App: undefined;
  Main: undefined;
  PostDetail: undefined;
  틈새시장: undefined;
};
